title: Garbage Collection
description: This is a collection of all the garbage which comes out of my mind.
author: Richard Vodden
author_email: richard@vodden.com
twitter_username: rvodden
github_username: rvodden
linkedin_username: rvodden
url: http://vodden.com/
baseurl: ""
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            comments: "true"

## Build Stuff

theme: minima
markdown: kramdown
highlight: rouge
kramdown:
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1

disqus:
  shortname: garbagecollection

pagintion: 5
exclude:
    - vendor
    - Gemfile
    - CNAME
    - Gemfile.lock

plugins:
    - jekyll-assets
    - jekyll-feed
