baseURL = "https://vodden.com/"
languageCode = "en-gb"
title = "Garbage Collection"
theme = "minima"
enableGitInfo = true
pygmentsUseClasses=true
googleAnalytics = "UA-89156251-1"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[params]
  Environment = "Production"
  Author = "Richard Vodden"
  email = "richard@vodden.com"
  Description = "This is a collection of all the garbage which comes out of my mind."
  githubUsername = "rvodden"
  twitterUsername = "rvodden"

[frontmatter]
  date = ["date", ":filename", "lastmod"]
  publishDate = ["publishDate", "date"]
  lastmod = [":git", "date"]

[markup]
  [markup.highlight]
    lineNos = true
    anchorLineNos = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
