source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-paginate-v2'
gem 'jekyll-titles-from-headings'
gem 'jekyll-assets'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-plantuml'
gem 'html-proofer'
gem 'uglifier'
gem 'therubyracer'
gem 'minima', :git => 'git://github.com/rvodden/minima.git', branch: 'master'
gem 'sprockets'
