source 'https://rubygems.org'
gem 'jekyll'
#gem 'jekyll-coffeescript'
#gem 'jekyll-gist'
#gem 'jekyll-github-metadata'
gem 'jekyll-paginate-v2'
#gem 'jekyll-relative-links'
#gem 'jekyll-optional-front-matter'
#gem 'jekyll-readme-index'
#gem 'jekyll-default-layout'
#gem 'jekyll-titles-from-headings'
gem 'jekyll-assets'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'html-proofer'
gem 'uglifier'
gem 'therubyracer'
gem 'minima', :git => 'git://github.com/rvodden/minima.git'
gem 'sprockets', '~> 4.0beto', {
  require: false
}
