version: 2
jobs:
    build:
        working_directory: ~/build
        environment:
            - USER_NAME: "Richard Vodden"
            - USER_EMAIL: "richard@vodden.com"
        docker:
            - image: circleci/ruby:2.4.3
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: bundle install --path vendor/bundle
            - run:
                name: Build Website
                command: bundle exec jekyll build
    

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
