version: 2
defaults: &defaults
    working_directory: ~/build
    environment:
        - USER_NAME: "Richard Vodden"
        - USER_EMAIL: "richard@vodden.com"
    docker:
        - image: circleci/ruby:2.4.3

jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: ~/build
            - run:
                name: Install Dependencies
                command: bundle check || bundle install
            - save_cache:
                key: bundle_{{ checksum "Gemfile.lock" }}
                paths:
                    - vendor/bundle
            - run:
                name: Build Website
                command: bundle exec jekyll build
    
    test:
        <<: *defaults
        requires:
            - build
        steps:
            - attach_workspace:
                at: ~/build
            - run:
                name: Validate HTML
                command: bundle exec htmlproofer ./_site --check-html --disable-external
    
    deploy:
        <<: *defaults
        requires:
            - test
        docker:
            image: circleci/ruby:2.4.3
        steps:
            - attach_workspace:
                at: ~/build
            - run:
                name: Deploy
                command: ~/build/scripts/deploy.sh

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - test
            - deploy:
                filters:
                    branches:
                        only: draft

